### ISSUE TITLE
Trying to open Dependencies.exe and nothing happens

### ISSUE THREAD

**Issue by rossinimartins** [lucasg/Dependencies#1]
Steps to reproduce:

\- Download either one of the released versions
\- Extract all the files from the zip
\- Double click `Dependencies.exe`

Expected behaviour: main windows show up.
Actual behaviour: nothing happens, as if I never tried to open it in the first place.

Environment details: recently reinstalled Windows 1709, build 16299.19

**Comment by kratzert** [comment]
Unfortunately same here for me on Windows 10 Version 1703 Build 15063.674

**Comment by lucasg** [comment]
OK I've reproduced the issue on a test VM, my money on a missing system dependency (ironic I know). I'll look into it this weekend.

**Comment by lucasg** [comment]
Okay I've pinned down the issue : I've mistakenly upload the debug build instead of the release build. Tell me if the issue is resolved on your side now.

As a side, note [`ClrPhLib` is necessarily built as `/MD(d)`](https://msdn.microsoft.com/en-us/library/ffkc918h.aspx) which means you may need to install [Microsoft Visual C++ 2015 Redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=53840) to make it work. I'll try to bundle it some way or another in the future.

**Comment by rossinimartins** [comment]
Yeah, it is working after the installation of the Microsoft Visual C++ 2015 Redistributable that you linked. Thanks for the feedback regarding this issue.
