### ISSUE TITLE
[Help] How to build this project on Dev machine

### ISSUE THREAD

**Issue by codingonHP** [lucasg/Dependencies#143]
I have cloned the repo and I am trying to build it locally but I am getting a lot of errors. What are the steps to build it locally.

**Comment by codingonHP** [comment]
Errors:
`The tag 'InterTabController' does not exist in XML namespace 'clr-namespace:Dragablz;assembly=Dragablz'. Line 44 Position 14.	DependenciesGui	C:\source\repos\Dependencies\DependenciesGui\MainWindow.xaml	44`

`'C:\source\repos\Dependencies\bin\Debug32\ClrPhlib.dll' could not be found	DependenciesLib	C:\source\repos\Dependencies\DependenciesLib\CSC	1	Active`

**Comment by lucasg** [comment]
That's weird I never had this issue, and I've compiled Dependencies on several computers.

The first issue lies entirely in third-party code (https://github.com/ButchersBoy/Dragablz) but I haven't updated in any way. Try to find out if the project is correctly loaded in VisualStudio

The second is more classic, I'm pretty sure another reason prevent VS from compiling ``ClrPhLib.dll``, and it fails ``DependenciesLib`` since it's dependent on it.

**Comment by codingonHP** [comment]
@lucasg Sure, let me see what I can do
