### ISSUE TITLE
dependencies gui dbghelp.dll _o_memset

### ISSUE THREAD

**Issue by evandrocoan** [lucasg/Dependencies#181]
I downloaded version 1.10 and I use Windows 8, but I got this when opening a dll:

![image](https://user-images.githubusercontent.com/5332158/117379808-b0e0d800-aeae-11eb-859f-15958ef8d6db.png)

What is this `dbghelp.dll` he is looking for?  

Is this related to https://github.com/lucasg/Dependencies/issues/108 Crash in undecorator ? When would a new version be released with that fix?

**Comment by lucasg** [comment]
Hmm, it is probably an issue between the `dbghelp.dll` I ship with `Dependencies` and your version of Windows 8 (which I never quite tested).

For testing purposes, do you run Windows 8 or Windows 8.1 ?
If you could give me the build number also it would help me (run `systeminfo` in a terminal)

**Comment by ronikeller** [comment]
I can reproduce the same issue on a "Windows Server 2012"

Detailed information:
- Windows Server 2012 R2 Standard (Build 6.3.9600), 64 bit
- Installed Visual Studio versions: 2010, 2017, 2019
- NO Debugging Tools installed (i.e. there is no folder "C:\ProgramFiles\Windows Kits\10\Debuggers\x64\")

As a workaround I can delete (or rename) the file "dbghelp.dll" from the installation directory of Dependencies.
In my case it will fall back to the pre-installed version of "dbghelp.dll" in C:\Windows\system32.

I guess the problem is that your included "dbghelp.dll" depends on many "api-ms-win-XXX" DLLs (I think they are all part of the VS2015 redistributables). But you included no all of them.
The missing ones (in my case various api-ms-win-core-XXX-l1-1-0.dll") will be used from the System folder.
Most probably the ones from the System folder are not compatible with your included "dbghelp.dll".

I think, best would be if you could prioritize the version from the System folder over your included one (similar to your check if there is a version from the Debugging Tools). Or is the default one missing some features?
Or would it be possible to also include a matching set of "api-ms-win-core-XXX" DLLs?

BTW: I really appreciate your tool, it helped me already to solve a lot of DLL issues! :-)

**Comment by evandrocoan** [comment]
I deleted the shipped dbghelp.dll and the problem was fixed. @ronikeller , thanks for sharing a fix.

@lucasg sorry for the delay, I am not reading my notifications from github for now (busy). I use windows 8 build 9200.

**Comment by lucasg** [comment]
Indeed, the dbghelp.dll I ship with Dependencies rely on a missing api minwin called `api-ms-win-crt-private-l1-1-0.dll` on win8.1:

![image](https://user-images.githubusercontent.com/2520861/129483249-e36eda93-a49e-4dfe-abd8-84a46b15a63a.png)

As suggested, now Dependencies tries to load from system32 folder : https://github.com/lucasg/Dependencies/commit/bcd50ce2593542eec22547b5622c9dc1d460e700, which fixed the issue

You'll have to wait the v1.11 release to get it though if you don't want to rebuild the binaries

**Comment by evandrocoan** [comment]
Thanks for fixing it!
