### ISSUE TITLE
.net dependency walker when managed code dll are being loaded

### ISSUE THREAD

**Issue by Pascal7z** [lucasg/Dependencies#20]
Hello, 
in a search for CLR based DLL's dependency walker your tool showed. A nice feature is not to crash on a compiled C# DLL - just showing the mscoree.dll dependency. 
A nice addition would be to walk through the CLR dependency tree when encountering such a DLL.

**Comment by lucasg** [comment]
Weird, both the v1.7 GUI and the CLI works for  `mscoree.dll`:

![image](https://user-images.githubusercontent.com/2520861/41498132-061e2900-7166-11e8-9f85-7338e40241f0.png)

Can you give me additional info about your crash, or maybe sending me your  `mscoree.dll` ? 

About your second point, `Win32` and `CLR` are two separate Windows subsystems, so it would be better to display the CLR dependency tree in a separate standalone tool IMO. Moreover I don't know enough about C# and CLR to properly display the information in a useful way.

**Comment by Pascal7z** [comment]
Dependencies works fine with mscoree.dll, and shows similar resultas as yours. 
What I mean is when try to see the dependencies of for example log4net.dll from the log4net nuget package, it will not show the .net assemblies log4net depends on. 
Something in fact ,net dependency walker which I found later : https://www.workshell.co.uk/products/netdepends/

**Comment by georgethejournalist** [comment]
If I understand it correctly you want to see the dependency of your dependency. I think this could be related to the bit from the readme that says (correct me if I'm wrong):
Dependencies currently does not recursively resolve child imports when parsing a new PE since it can be really memory-hungry to do so ( it can over a GB even for "simple" PEs ). This behaviour can be overriden (app-wide) via a property located in "Options->Properties->Tree build behaviour".

Tree build behaviours available :

-     ChildOnly (default) : only process PE child imports and nothing beyond.
-     RecursiveOnlyOnDirectImports : do not process delayload dlls.
-     Recursive : Full recursive analysis. You better have time and RAM on your hands if you activate this

**Comment by lucasg** [comment]
@Pascal7z : I've added assembly enumeration for C# binaries with commit https://github.com/lucasg/Dependencies/commit/b5278e45e491e2c1d94c9250d970cd59ede0d5c9. This will be available in the next release.

Before :

![image](https://user-images.githubusercontent.com/2520861/44101483-d2a7bcb6-9fe7-11e8-98eb-197bd6d3ea67.png)

After:

![image](https://user-images.githubusercontent.com/2520861/44101496-da2bd882-9fe7-11e8-9e6c-fb3f63fd58fa.png)
