### ISSUE TITLE
32 bit dlls used by python projects are shown with question mark

### ISSUE THREAD

**Issue by mathog** [lucasg/Dependencies#30]
I built Pymol on a W7 system using mingw32 (msys2) where it worked OK.  Transferred it to a W10 64 bit system where it didn't work correctly (it is not drawing the molecule, everything else seems OK).  Tried to see if there were dlls missing with "dependencies" starting with __cmd.pyd and it shows all of those transferred with the package as missing, including libpython2.7.dll.  Demonstrated that that was not missing by starting the application with that renamed to hide_libpython2.7.dll, where it failed immediately, versus with the regular name, where it ran more or less normally.   

Tried to run dependencies on the W7 32 bit system where it was built but the dependencies downloads were all 64 bit, so the binary wouldn't run.  

Ran dependencies on python2.7.exe on the W10 system, which is used by __cmd.pyd, and that did find libpython2.7.dll and traced  into it.  (no question mark).

Ran dependencies on libpython2.7.dll on the W10 system, and that showed links to some of the other dll's not found originally (no question mark).

So, the issue seems to be that dependencies is missing or ignoring some path variable.  Tried adding a path to where these dll's live before starting dependencies:

`set PATH=%PATH%C:\temp\blah\bin;
`
then starting dependencies, but it didn't help.

On the W10 system tried running dependencies on .../Numpy/core/_umath_tests.pyd and it was just like pymol - it couldn't find libpython2.7.dll.

It may be that the same thing would happen with 64 bit dlls built on the W10 system which were also referred to from *.pyd files.  That has not yet been tested.

**Comment by mathog** [comment]
Note - also tested some *pyd files from a PyMol "incentive" build (the package is open source but not public domain, the vendor also distributes binaries) and had the same problem as above - the linked dll's are not found by "dependencies" and show up with a question mark.  Since that incentive build works OK on the W10 64 bit system I believe it finds all of its dll's, so "dependencies" not doing so is a problem with "dependencies".

**Comment by lucasg** [comment]
I don't know if it related to your issue, but I recently tracked a pretty freaky bug analyzing 64-bit binaries with a 32-bit build of Dependencies. Example with Python 64-bit :

![image](https://user-images.githubusercontent.com/2520861/45241294-21915a00-b2ec-11e8-90b8-579ff98d11ad.png)

`python27.dll` is not correctly recognized since wow64 applications wanting to access `C:\Windows\system32` (where 64-bit system natives dlls are located) are redirected to `C:\Windows\syswow64` (32-bit equivalents for natives dll), for retro-compatibility purposes. The issue here there is no `python27.dll` in the `syswow64` folder.

The fix was to force direct access to the native filesystem. You can try it by downloading here https://ci.appveyor.com/project/lucasg/dependencies/build/1.7.200

![image](https://user-images.githubusercontent.com/2520861/45241539-21de2500-b2ed-11e8-8dde-3993ca4834d0.png)
