### ISSUE TITLE
Crashes with NullReferenceException

### ISSUE THREAD

**Issue by Const-me** [lucasg/Dependencies#37]
I'm attaching the call stack.

[stack.txt](https://github.com/lucasg/Dependencies/files/2506584/stack.txt)

**Comment by lucasg** [comment]
Hmm, the only reason why this crash appear would be `ImportDllName` being set to `null`, which means having a DLL with an import name that make the PE parser choke ... Can you provide a test binary to investigate this issue a bit further ?

I can always put some null check safeguard, but it amount to sweep the issue under the rug.

**Comment by Const-me** [comment]
http://www.hddguru.com/software/HDD-Raw-Copy-Tool/

**Comment by lucasg** [comment]
Okay, the executable is really wacky in terms of PE parsing, I'm pretty sure the packer used to make the application portable does not respect the PE specs, but the NT loader seems to get on fine.

I've found a workaround, but I honestly don't know if it a "feature" or just a silent bugfix from Microsoft. In the meantime, `Dependencies` now gracefully accept invalid import entries :

![image](https://user-images.githubusercontent.com/2520861/47387516-dc947c00-d70f-11e8-8134-220be1fdd1a5.png)


You can download an up-to-date version here : https://ci.appveyor.com/api/buildjobs/6434w4kmpy0kdsag/artifacts/output%2FDependencies_x64_Release.zip

**Comment by lucasg** [comment]
Okay, after some investigation it appears the HDDGuru's tool PE header is incorrect an store its delay load configuration as VA instead of RVA. This is probably a `Delphi` issue, the compiler used to generate the portable executable (the bug is pretty mild since the compiler also generate a correct delay load resolver).

Some tools like IDA correctly parse the incorrect header since they rely on VA, but ProcessHacker's `mapimg` rely on RVA and I won't bother writing a workaround for something that's broken.
