### ISSUE TITLE
Modify Module Search Order

### ISSUE THREAD

**Issue by cschermerhorn** [lucasg/Dependencies#38]
Is there a way to modify the module search order when running the gui after selecting a dll?  I see that there is a shortcut for viewing the search order (Maj + m), but was not seeing a clear way to add a directory to the list that appears in the dialog window.  This looks more informational than something I would be able to modify.

**Comment by lucasg** [comment]
Unfortunately not for now, but it's in the backlog. There is currently application-wide settings, but no per binary configuration which can store what you ask. Once I've done it, it should be easier to add user supplied directories.

L.

**Comment by lucasg** [comment]
You can now modify the binary's working directory and add custom search folders by clicking "Options/Customize search folders" :

![image](https://user-images.githubusercontent.com/2520861/49115443-1e7a8a00-f29b-11e8-9b35-892339890259.png)

However you can't modify the module search order since Dependencies is trying to replicate NT's loader behavior.

**Comment by cschermerhorn** [comment]
Great!  Thanks for implementing this, will definitely be useful in my use cases.
