### ISSUE TITLE
Missing DependenciesAppx_TemporaryKey.pfx

### ISSUE THREAD

**Issue by apsteger** [lucasg/Dependencies#46]
Rebuilding all from VS2017 I receive: 

Certificate file 'DependenciesAppx_TemporaryKey.pfx' not found.	DependenciesAppx	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Microsoft\VisualStudio\v15.0\AppxPackage\Microsoft.AppXPackage.Targets

**Comment by lucasg** [comment]
Yeah, you're not "supposed" to build `DependenciesAppx` in order to create an `Appx` package (that's something I tried to do but its expensive as hell to buy an EV certificate). You can use `DependenciesGui.exe` without it.

If you still want to do it, create a `.pfx` file (its like a `.p12` file with private and public key info) called `DependenciesAppx_TemporaryKey.pfx` in the `DependenciesAppx` subfolder and you should be able to build it fine.

Here's how to create a pfx file : `https://knowledge.digicert.com/solution/SO26065.html`
