### ISSUE TITLE
NullReferenceException in Travis CI (Windows Server Core)

### ISSUE THREAD

**Issue by native-api** [lucasg/Dependencies#81]
Reproduction steps:
https://travis-ci.org/native-api/test_travis/builds/565301766

Travis CI [uses Windows Server Core 1803](https://docs.travis-ci.com/user/reference/windows/#windows-version).

**Comment by lucasg** [comment]
Ok, I don't know the root cause, but I think this issue has been fixed between 1.9 and now (master)
I should release the 1.10 in order to previous future duplicate issue but in the mean time you can always download build artifacts : https://ci.appveyor.com/project/lucasg/dependencies/builds/26283828/job/tqfq86cqtgyykjbd/artifacts

**Comment by native-api** [comment]
Confirmed that with the HEAD version, there's no error. The output looks strange though and it's MASSIVE (the build was terminated after reaching the log size limit of a few MB).

The title problem is fixed though so I'm closing this ticket.
