### ISSUE TITLE
When closing a file, the file should be able to be deleted

### ISSUE THREAD

**Issue by vanxining** [lucasg/Dependencies#9]
Awesome tool!

But when we open and close a file in the program, the corresponding file can not be deleted in the Windows Explorer without exiting Dependencies.

Thanks!

**Comment by lucasg** [comment]
I'm aware of the issue : it comes from the fact that `phlib` maps the file in memory in order to resolve RVAs and metadatas, consequently locking the file (it's actually a Win32 limitation). 

I'll try to find a workaround (either by unmaping aggressively, or copy the input file in a temporary local storage).

L.

**Comment by lucasg** [comment]
Commit https://github.com/lucasg/Dependencies/commit/969de216fac1e5526a2e8d53a7126095141c9783 solve this issue by building a cache on disk instead of loading original files. CPU performance has taken a bit of a hit, but it's bearable.
