### ISSUE TITLE
Executable file has no verion flag(64 or 32) compared to depends.

### ISSUE THREAD

**Issue by CrawlWu** [lucasg/Dependencies#92]

**Comment by CrawlWu** [comment]
![image](https://user-images.githubusercontent.com/9069122/67547792-a2025c80-f732-11e9-811a-e10f6ffd5f5b.png)

**Comment by lucasg** [comment]
Yes because it makes 0 sense for the NT loader to load a 64-bit module as a dependency of a 32-bit dll/exe. The only exception is 64-bit ntdll.dll which is always loaded since it is necessary to talk with the NT kernel.

If you still need to know with version flag you're currently looking at, I suggest looking at the "Machine" field in the Module listview :
![image](https://user-images.githubusercontent.com/2520861/68030919-cfaf4e80-fcba-11e9-8377-3ab679278f53.png)

**Comment by CrawlWu** [comment]
Sorry, I missed it.

**Comment by lucasg** [comment]
no big deal 😄

**Comment by agolks** [comment]
the issue is not making no sense. the issue is having a wrong architecture in PATH. and showing the 64/32bit flag directly in the main view makes it really more easy to see why your dll is not loaded.
"ah, oh, it's finding the 64bit dll, while i'm checking a 32bit exe..."
